import fs from 'node:fs';
import vm from 'node:vm';
const file = new URL('../scripts/autonomous-source-loader.mjs', import.meta.url);
let src = fs.readFileSync(file, 'utf8');
const start = src.indexOf('function sourceValueIsPreserved');
const end = src.indexOf('\nfunction comparisonPair', start);
const fnText = src.slice(start, end) + '\nthis.sourceValueIsPreserved = sourceValueIsPreserved;';
const context = {};
vm.createContext(context);
vm.runInContext(fnText, context);
const f = context.sourceValueIsPreserved;
const baseSource = {A:{originItem:{itemPath:null, actionIndex:null}, name:'Open'}};
const omitted = {A:{originItem:{}, name:'Open'}};
const undefinedKeys = {A:{originItem:{itemPath:undefined, actionIndex:undefined}, name:'Open'}};
const wrong = {A:{originItem:{itemPath:'x', actionIndex:null}, name:'Open'}};
if (!f(omitted, baseSource)) throw new Error('omitted null fields should be preserved');
if (!f(undefinedKeys, baseSource)) throw new Error('undefined null fields should be preserved');
if (f(wrong, baseSource)) throw new Error('real non-null divergence must remain red');
console.log('P2.12h.2d TESTS GREEN: originItem null accepts omitted or undefined runtime values only; real divergences remain strict.');
